config/routes.rb
Rails.application.routes.draw do
  resources :warriors, only: [:index, :new, :create]
  resources :farmers, only: [:index, :new, :create]
  devise_for :villagers
  root 'warriors#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resource :weather_prophecies, only: [:show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farmer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: farmers
#
#  id           :bigint(8)        not null, primary key
#  crop         :enum             not null
#  harvest_time :enum             not null
#

class Farmer < ApplicationRecord
  enum crop: {
    grain: 'grain',
    cheese: 'cheese',
    meat: 'meat',
    wool: 'wool'
  }

  enum harvest_time: {
    january: 'january',
    february: 'february',
    march: 'march',
    april: 'april',
    may: 'may',
    june: 'june',
    july: 'july',
    august: 'august',
    september: 'september',
    october: 'october',
    november: 'november',
    december: 'december'
  }

  has_one :villager, as: :villagerable

  validates :crop, :harvest_time, presence: true
end

app/models/villager.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: villagers
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  villagerable_type      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  villagerable_id        :integer
#
# Indexes
#
#  index_villagers_on_email                                  (email) UNIQUE
#  index_villagers_on_reset_password_token                   (reset_password_token) UNIQUE
#  index_villagers_on_villagerable_type_and_villagerable_id  (villagerable_type,villagerable_id)
#

class Villager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :villagerable, polymorphic: true, optional: true, validate: true
end

app/models/warrior.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: warriors
#
#  id               :bigint(8)        not null, primary key
#  raids            :integer          default(0)
#  role             :enum             default("shieldman")
#  weapon_of_choice :enum             default("axe")
#

class Warrior < ApplicationRecord
  enum weapon_of_choice: {
    sword: 'sword',
    axe:   'axe',
    spear: 'spear'
  }

  enum role: {
    shieldman: 'shieldman',
    spearman:  'spearman',
    berserker: 'berserker'
  }

  has_one :villager, as: :villagerable

  validates :raids, numericality: { greater_than_or_equal_to: 0 }
  validates :weapon_of_choice, :role, presence: true
end

app/models/weather_prophecy.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: weather_prophecies
#
#  id          :bigint(8)        not null, primary key
#  rain        :enum             default("moderate")
#  temperature :enum             default("moderate")
#  wind        :enum             default("moderate")
#  created_at  :date
#

class WeatherProphecy < ApplicationRecord
  enum rain: {
    heavy: 'heavy',
    moderate: 'moderate',
    none: 'none'
  }, _suffix: true

  enum temperature: {
    cold: 'cold',
    moderate: 'moderate',
    hot: 'hot'
  }, _suffix: true

  enum wind: {
    strong: 'strong',
    moderate: 'moderate',
    light: 'light'
  }, _suffix: true

  validates :rain, :temperature, :wind, :created_at, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_villager!
end

app/controllers/farmers_controller.rb
# frozen_string_literal: true

class FarmersController < ApplicationController
  def index
    render locals: { farmers: Farmer.all }
  end

  def new
    render locals: { farmer: Farmer.new }
  end

  def create
    RegisterProfession.call(profession_class: Farmer, params: farmer_params, villager: current_villager)
    redirect_to farmers_path, notice: "#{current_villager.email} was successfully registerd as farmer."
  end

  private

  def farmer_params
    params.require(:farmer).permit(:crop, :harvest_time)
  end
end

app/controllers/warriors_controller.rb
# frozen_string_literal: true

class WarriorsController < ApplicationController
  def index
    render locals: { warriors: Warrior.all }
  end

  def new
    render locals: { warrior: Warrior.new }
  end

  def create
    RegisterProfession.call(profession_class: Warrior, params: warrior_params, villager: current_villager)
    redirect_to warriors_path, notice: 'Warrior was successfully created.'
  end

  private

  def warrior_params
    params.require(:warrior).permit(:role, :weapon_of_choice)
  end
end

app/controllers/weather_prophecies_controller.rb
# frozen_string_literal: true

class WeatherPropheciesController < ApplicationController
  def show
    render locals: { prophecy: WeatherProphecyService.new.call }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/farmers/_form.html.erb
<%= form_with(model: farmer, local: true) do |form| %>
  <% if farmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(farmer.errors.count, "error") %> prohibited this farmer registration from being saved:</h2>

      <ul>
      <% farmer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    Crop:
    <%= form.select(:crop) do %>
      <%= options_for_select(Farmer.crops.values, Farmer.crops.values.first) %>
    <% end %>
  </div>
  <div>
    Harvest time:
    <%= form.select(:harvest_time) do %>
      <%= options_for_select(Farmer.harvest_times.values, Farmer.harvest_times.values.first) %>
    <% end %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/farmers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Farmers</h1>

<table>
  <thead>
    <tr>
      <th>Contact</th>
      <th>Crop</th>
      <th>Month of Harvest</th>
    </tr>
  </thead>

  <tbody>
    <% farmers.each do |farmer| %>
      <tr>
        <td><%= farmer.villager.email %></td>
        <td><%= farmer.crop %></td>
        <td><%= farmer.harvest_time.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to 'Become a farmer!', new_farmer_path, method: :get %>

app/views/farmers/new.html.erb
<h1>Register as farmer</h1>

<%= render 'form', farmer: farmer %>

<%= link_to 'Back', farmers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valhalla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Warriors', warriors_path %></li>
        <li><%= link_to 'Farmers', farmers_path %></li>
      </ul>
    </nav>
    
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/warriors/_form.html.erb
<%= form_with(model: warrior, local: true) do |form| %>
  <% if warrior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warrior.errors.count, "error") %> prohibited this warrior from being saved:</h2>

      <ul>
      <% warrior.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    Weapon:
    <%= form.select(:weapon_of_choice) do %>
      <%= options_for_select(Warrior.weapon_of_choices.values, Warrior.weapon_of_choices.fetch(:axe)) %>
    <% end %>
  </div>
  <div>
    Role:
    <%= form.select(:role) do %>
      <%= options_for_select(Warrior.roles.values, Warrior.roles.fetch(:shieldman)) %>
    <% end %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warriors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Warriors</h1>

<table>
  <thead>
    <tr>
      <th>Contact</th>
      <th>Class</th>
      <th>Weapon</th>
      <th>Raids</th>
    </tr>
  </thead>

  <tbody>
    <% warriors.each do |warrior| %>
      <tr>
        <td><%= warrior.villager.email %></td>
        <td><%= warrior.role %></td>
        <td><%= warrior.weapon_of_choice %></td>
        <td><%= warrior.raids %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_to 'Become a warrior!', new_warrior_path, method: :get %>

app/views/warriors/new.html.erb
<h1>New Warrior</h1>

<%= render 'form', warrior: warrior %>

<%= link_to 'Back', warriors_path %>

app/views/weather_prophecies/show.html.erb
<h2>Today's <%= Date.current %> Weather Prophecy<h2/>
<h3>Runes has spoken</h3>
<p> 
  Temperature will be <%= prophecy.temperature %>, with <%= prophecy.rain %> rain and <%= prophecy.wind %> wind.
</p>